model_list:
  - model_name: gemini/*
    litellm_params:
      model: gemini/*
      api_key: AIzaSyA80y3HYIyqtPE5Db2RmLHEGE917ddIfWM

router_settings:
  model_group_alias:
    {
      'gemini-2.5-pro': 'gemini/gemini-2.5-pro',
      'gemini-2.5-flash': 'gemini/gemini-2.5-flash',
      'gemini-2.5-flash-lite': 'gemini/gemini-2.5-flash-lite',
    }
